
-- Generated: 2018-01-14 23:55
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Pablo Cumpián Díaz

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuarios` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Contrasena` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Conversacion` (
  `Mensaje` VARCHAR(45) NULL DEFAULT NULL,
  `user` INT(10) UNSIGNED NOT NULL,
  INDEX `idUsuario1_idx` (`user` ASC),
  CONSTRAINT `idUsuario1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Usuario` (`idUsuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Sesion` (
  `idSesion` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `IdUsuario_idx` (`idUsuario` ASC),
  CONSTRAINT `IdUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;